name: aichatapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.5+5
environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  app_tracking_transparency: ^2.0.3
  appsflyer_sdk: ^6.9.3
  change_app_package_name: ^1.1.0
  cloud_firestore: ^4.3.1
  cloud_functions: ^4.0.7
  cupertino_icons: ^1.0.2
  duration: ^3.0.12
  extended_image: ^8.0.2
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter:
    sdk: flutter
  flutter_app_badger: ^1.5.0
  flutter_bounce: ^1.1.0
  flutter_facebook_auth: ^5.0.7
  flutter_inapp_purchase: ^5.3.1
  flutter_screenutil: ^5.8.4
  flutter_svg: ^1.1.6
  get: 4.6.5
  get_it: ^7.2.0
  google_sign_in: ^5.4.3
  http: ^0.13.5
  in_app_purchase: ^3.1.1
  in_app_review: ^2.0.6
  permission_handler: ^10.2.0
  rating_dialog: ^2.0.4
  share_plus: ^6.3.0
  shared_preferences: ^2.0.16
  sign_in_with_apple: ^4.3.0
  tenjin_sdk: ^1.0.2
  url_launcher: ^6.1.7
  webview_flutter: ^4.0.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/image/
